const express = require('express');
const auth = require('../../middlewares/auth');
const { productTypeController } = require('../../controllers');

const router = express.Router();

router
  .route('/')
  .post(
    auth(
      'superadmin',
      'manufacture',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer'
    ),
    productTypeController.createProductType
  )
  .get(
    auth(
      'superadmin',
      'manufacture',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer'
    ),
    productTypeController.queryProductType
  );

router
  .route('/:id')
  .get(
    auth(
      'superadmin',
      'manufacture',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer'
    ),
    productTypeController.getProductTypeById
  )
  .patch(
    auth(
      'superadmin',
      'manufacture',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer'
    ),
    productTypeController.updateProductTypeById
  )
  .delete(
    auth(
      'superadmin',
      'manufacture',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer',
      'wholesaler',
      'retailer'
    ),
    productTypeController.deleteProductTypeById
  );

module.exports = router;
