[
    {
        "sizeType": "Size Set",
        "sizeChart": [
            "Standard Size",
            "Brand Size",
            "Chest Size",
            "Shoulder Size",
            "Front Length",
            "Neck Size",
            "W/S Price",
            "Rtl Price",
            "MRP"
        ],
        "Sizes": [
            { "wordSize": null, "size": "5XS" },
            { "wordSize": null, "size": "4XS" },
            { "wordSize": null, "size": "3XS" },
            { "wordSize": null, "size": "2XS" },
            { "wordSize": null, "size": "XS" },
            { "wordSize": null, "size": "S/36" },
            { "wordSize": null, "size": "37" },
            { "wordSize": null, "size": "M/38" },
            { "wordSize": null, "size": "39" },
            { "wordSize": null, "size": "L/40" },
            { "wordSize": null, "size": "41" },
            { "wordSize": null, "size": "XL/42" },
            { "wordSize": null, "size": "43" },
            { "wordSize": null, "size": "2XL/44" },
            { "wordSize": null, "size": "45" },
            { "wordSize": null, "size": "3XL/46" },
            { "wordSize": null, "size": "47" },
            { "wordSize": null, "size": "4XL/48" },
            { "wordSize": null, "size": "49" },
            { "wordSize": null, "size": "5XL/50" },
            { "wordSize": null, "size": "51" },
            { "wordSize": null, "size": "6XL/52" },
            { "wordSize": null, "size": "53" },
            { "wordSize": null, "size": "7XL/54" },
            { "wordSize": null, "size": "55" },
            { "wordSize": null, "size": "8XL/56" },
            { "wordSize": null, "size": "57" },
            { "wordSize": null, "size": "Free" }
        ]
    },
    {
        "sizeType": "Waist Size Set",
        "sizeChart": [
            "Standard Size",
            "Brand Size",
            "Waist Size Set (Standard Size)",
            "Waist (in)",
            "Inseam (in)",
            "Length (in)",
            "Rise (in)",
            "Length",
            "Width",
            "Height",
            "Weight",
            "W/S Price",
            "Rtl Price",
            "MRP"
        ],
        "Sizes": [
            { "wordSize": null, "size": "22" },
            { "wordSize": null, "size": "23" },
            { "wordSize": null, "size": "24" },
            { "wordSize": null, "size": "25" },
            { "wordSize": null, "size": "26" },
            { "wordSize": null, "size": "27" },
            { "wordSize": null, "size": "28" },
            { "wordSize": null, "size": "29" },
            { "wordSize": null, "size": "30" },
            { "wordSize": null, "size": "31" },
            { "wordSize": null, "size": "32" },
            { "wordSize": null, "size": "33" },
            { "wordSize": null, "size": "34" },
            { "wordSize": null, "size": "35" },
            { "wordSize": null, "size": "36" },
            { "wordSize": null, "size": "37" },
            { "wordSize": null, "size": "38" },
            { "wordSize": null, "size": "39" },
            { "wordSize": null, "size": "40" },
            { "wordSize": null, "size": "41" },
            { "wordSize": null, "size": "42" },
            { "wordSize": null, "size": "43" },
            { "wordSize": null, "size": "44" },
            { "wordSize": null, "size": "45" },
            { "wordSize": null, "size": "46" },
            { "wordSize": null, "size": "47" },
            { "wordSize": null, "size": "48" },
            { "wordSize": null, "size": "49" },
            { "wordSize": null, "size": "50" }
        ]
    }
]
